### ISSUE TITLE
overflow 

### ISSUE THREAD

**Issue by aayusranjan** [DayMrz/pacto-names-react#1]
Great, I really enjoyed while typing my name, but there is some issue after writing to many letters its overflowing
![Screenshot 2022-06-04 163411](https://user-images.githubusercontent.com/63737303/171996390-3fd16efb-96dd-4d96-aa56-2af0b42e793c.png)

**Comment by DayMrz** [comment]
Hi Ayush,
Thanks for taking the time to review my project. :3
I appreciate your feedback. 

Day ✌
